# Spécifie l'image parente à partir de laquelle nous construisons
FROM nginx:alpine

# Définit le répertoire de travail pour les instructions qui suivent
WORKDIR /var/www

# Exécute nginx
CMD ["nginx"]

# Informe Docker que le conteneur écoute sur les ports réseau spécifiés au moment de l'exécution
EXPOSE 80